# This is a basic workflow that is manually triggered

name: Auto Delete Branch

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: delete-merged-branch-asdf
      # You may pin to the exact commit or the version.
      # uses: zjutszl/my-cool-action@784f885c93e777741212b0672c728bcd4922fcb5
      uses: zjutszl/my-cool-action@v1.0.0-rc.2
          
